name: Fly Deploy 
on:
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main
    types: [opened, synchronize]

jobs: 
  simple_fly_deploy:
    runs-on: ubuntu-latest 
    if: ${{ github.event_name == 'push' }}
    steps: 
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master 
      - run: flyctl deploy --remote-only 
        env: 
         FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}

